export type ApprovalStatus = 'pending' | 'under_review' | 'approved' | 'rejected';
export type ApprovalAction = 'approve' | 'reject' | 'under_review';

export interface CustomerApprovalRow {
  id: number | string;
  customerId?: string | null;
  firstName: string;
  lastName: string;
  gender?: string | null;
  phone: string;
  emergencyContact?: string | null;
  email?: string | null;
  city?: string | null;
  area?: string | null;
  pincode?: string | null;
  serviceCategory?: string | null;
  vehicleType?: string | null;
  vehicleSubType?: string | null;
  fuelType?: string | null;
  tripPreference?: string | null;
  vehicleNumber?: string | null;
  rcNumber?: string | null;
  rcExpiry?: string | null;
  insuranceNumber?: string | null;
  insuranceExpiry?: string | null;
  pucNumber?: string | null;
  pucExpiry?: string | null;
  fitnessNumber?: string | null;
  fitnessExpiry?: string | null;
  permitNumber?: string | null;
  permitExpiry?: string | null;
  dlNumber?: string | null;
  dlExpiry?: string | null;
  idProofType?: string | null;
  idProofNumber?: string | null;
  idProofExpiry?: string | null;
  createdByName?: string | null;
  createdByEmail?: string | null;
  createdByPhone?: string | null;
  isSelfRegistered?: boolean;
  uploadedFiles?: string | null;
  bundleTypes?: string | string[] | null;
  bundleDiscount?: number | null;
  rentalVehiclePref?: string | null;
  rentalDuration?: string | null;
  rentalPickupZone?: string | null;
  driverHireCount?: string | null;
  driverHireShift?: string | null;
  driverHireBudget?: string | null;
  additionalVehicles?: string | null;
  parcelComboTypes?: string | null;
  parcelMaxWeight?: string | null;
  parcelRadiusPref?: string | null;
  cargoCoRideMax?: string | null;
  cargoCoRideHaulPref?: string | null;
  cargoCoRideRatePref?: string | null;
  status: ApprovalStatus | string;
  adminNotes?: string | null;
  submittedAt?: string | null;
  createdAt?: string | null;
  updatedAt?: string | null;
}

export type CustomerOnboardingRow = CustomerApprovalRow & { sno: number };
